// AUTH
export const AUTH_LOGIN = 'AUTH LOGIN';
export const AUTH_LOGOUT = 'AUTH LOGOUT';
export const AUTH_CHEKING_FINISH = 'AUTH CHEKING FINISH';

// AMBIENTS AND SCHEDULES
export const LOAD_AMBIENTS = 'LOAD AMBIENTS';
export const LOAD_AMBIENT  = 'LOAD AMBIENT';
export const LOAD_AMBIENTS_SCHEDULES = 'LOAD AMBIENTS SCHEDULES';
export const LOAD_AMBIENT_SCHEDULES = 'LOAD AMBIENT SCHEDULES';

// COMPETENCIES
export const LOAD_COMPETENCIES = 'LOAD COMPETENCIES';
export const LOAD_COMPETENCIE = 'LOAD COMPETENCIE';

// GROUPS
export const LOAD_GROUPS = 'LOAD GROUPS';
export const LOAD_GROUP = 'LOAD GROUP';
export const LOAD_GROUPS_SCHEDULES = 'LOAD GROUPS SCHEDULES';
export const LOAD_GROUP_SCHEDULES = 'LOAD GROUP SCHEDULES';

// MODALITIES
export const LOAD_MODALITIES = 'LOAD MODALITIES';
export const LOAD_MODALITIE = 'LOAD MODALITIE';

// FORMATIONPROGRAMS
export const LOAD_FORMATIONPROGRAMS = 'LOAD FORMATIONPROGRAMS';
export const LOAD_FORMATIONPROGRAM = 'LOAD FORMATIONPROGRAM';

// LEARNINGRESULTS
export const LOAD_LEARNINGRESULTS = 'LOAD LEARNINGRESULTS';
export const LOAD_LEARNINGRESULT = 'LOAD LEARNINGRESULT';

// FORMATIONPROGRAMTYPES
export const LOAD_FORMATIONPROGRAMTYPES = 'LOAD FORMATIONPROGRAMTYPES';
export const LOAD_FORMATIONPROGRAMTYPE = 'LOAD FORMATIONPROGRAMTYPE';

// MUNICIPALITIES
export const LOAD_MUNICIPALITIES = 'LOAD MUNICIPALITIES';
export const LOAD_MUNICIPALITIE = 'LOAD MUNICIPALITIE';

//ZONES
export const LOAD_ZONES = 'LOAD ZONES';
export const LOAD_ZONE = 'LOAD ZONE';

//CONTRACTTYPES
export const LOAD_CONTRACTTYPES = 'LOAD CONTRACTTYPES';
export const LOAD_CONTRACTTYPE = 'LOAD CONTRACTTYPE';

//POSITIONS
export const LOAD_POSITIONS = 'LOAD POSITIONS';
export const LOAD_POSITION = 'LOAD POSITION';

//ROLS
export const LOAD_ROLS = 'LOAD ROLS';
export const LOAD_ROL = 'LOAD ROL';

//DESPROGRAMMINGREASONS
export const LOAD_DESPROGRAMMINGREASONS = 'LOAD DESPROGRAMMINGREASONS';
export const LOAD_DESPROGRAMMINGREASON = 'LOAD DESPROGRAMMINGREASON';

//USERS
export const LOAD_USERS = 'LOAD USERS';
export const LOAD_USER = 'LOAD USER';

//TEMPORARYUSERACTIVITIES
export const LOAD_TEMPORARYUSERACTIVITIES = 'LOAD TEMPORARYUSERACTIVITIES';
export const LOAD_TEMPORARYUSERACTIVITIE = 'LOAD TEMPORARYUSERACTIVITIE';

//TYPEACTIVITIES 
export const LOAD_TYPEACTIVITIES = 'LOAD TYPEACTIVITIES';
export const LOAD_TYPEACTIVITIE = 'LOAD TYPEACTIVITIE';

//PROGRAMATIONS
export const LOAD_PROGRAMATIONS = 'LOAD PROGRAMATIONS';
export const LOAD_PROGRAMATION = 'LOAD PROGRAMATION';